language: node_js
sudo: false

node_js:
  - '7'
  - '8'
  - '9'

after_success:
  - npm run coverage
  - npm i coveralls
  - cat ./coverage/lcov.info | coveralls

notifications:
  email:
    on_success: never
